image: image-registry.openshift-image-registry.svc:5000/openshift/s2i-nodejs-oc:latest

stages:
  - deploy

.deploy: &deploy
  before_script:
    - oc login --username="$OPENSHIFT_USERNAME" --password="$OPENSHIFT_PASSWORD" --server="$OPENSHIFT_SERVER" --insecure-skip-tls-verify
    - oc project "$OPENSHIFT_NAMESPACE"
  script:
    - "oc rsync jar keycloak-64bd49db8c-qlpg5:opt/jboss/keycloak/standalone/deployments/"
    

Deploy:
  <<: *deploy
  stage: deploy
  environment:
    name: develop
    url: https://$OPENSHIFT_DOMAIN
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_ROOT_NAMESPACE == "thebrewery-okd4-prod"
      when: manual  
